<div class="btn-bar">
	<a href="/login" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i> <?php echo lang('back'); ?></a>
</div>

<form action="/login/forgot_password" method="post" class="form-horizontal">
	<fieldset>		
		<div class="form-group">
			<label for="email" class="col-sm-2 control-label"><?php echo lang('forgot_password.email'); ?></label>
			<div class="col-sm-3">
				<input type="email" name="email" id="email" value="<?php echo ($this->input->get('email') === FALSE) ? set_value('email') : $this->input->get('email'); ?>" class="form-control" required>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-5">
				<button class="btn btn-primary" type="submit"><?php echo lang('forgot_password.submit'); ?></button>
			</div>
		</div>
	</fieldset>
</form>