<form action="" method="post" class="form-horizontal">
	<fieldset>		
		<div class="form-group">
			<label for="new_password" class="col-sm-2 control-label"><?php echo lang('reset_password.new_password'); ?></label>
			<div class="col-sm-3">
				<input type="password" name="new_password" id="new_password" value="" class="form-control">
			</div>
		</div>
		
		<div class="form-group">
			<label for="new_password_conf" class="col-sm-2 control-label"><?php echo lang('reset_password.new_password_conf'); ?></label>
			<div class="col-sm-3">
				<input type="password" name="new_password_conf" id="new_password_conf" value="" class="form-control">
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-5">
				<button class="btn btn-primary" type="submit"><?php echo lang('reset_password.submit'); ?></button>
			</div>
		</div>
	</fieldset>
</form>