<p>Door veiligheids maatregelen van het beveiligen van uw wachtwoord aangepast zijn, is het verplicht uw wachtwoord opnieuw in te stellen.</p> <br />

<form action="<?php echo base_url(); ?>login/reset_password" method="post" class="form-horizontal">
	<fieldset>		
		<div class="control-group">
			<label for="username" class="control-label">Gebruikersnaam</label>
			<div class="controls">
				<input type="text" name="username" id="username" value="<?php echo ($this->input->get('username') === FALSE) ? set_value('username') : $this->input->get('username'); ?>" class="input-xlarge">
			</div>
		</div>
		
		<div class="control-group">
			<label for="old_password" class="control-label">Oud wachtwoord</label>
			<div class="controls">
				<input type="password" name="old_password" id="old_password" value="" class="input-xlarge">
			</div>
		</div>
		
		<div class="control-group">
			<label for="new_password" class="control-label">Nieuw wachtwoord</label>
			<div class="controls">
				<input type="password" name="new_password" id="new_password" value="" class="input-xlarge">
			</div>
		</div>
		
		<div class="control-group">
			<label for="new_password_conf" class="control-label">Herhaal nieuw wachtwoord</label>
			<div class="controls">
				<input type="password" name="new_password_conf" id="new_password_conf" value="" class="input-xlarge">
			</div>
		</div>

		<div class="form-actions">
			<button class="btn btn-primary" type="submit">Wijzig wachtwoord</button>
		</div>
	</fieldset>
</form>