<div class="btn-bar">
	<a href="/clients" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i> Terug</a>
</div>

<form action="/clients/add" method="post" class="form-horizontal">
	<fieldset>
		<div class="form-group">
			<label for="name" class="col-sm-2 control-label">Naam</label>
			<div class="col-sm-5">
				<input type="text" name="name" id="name" value="<?php echo set_value('name'); ?>" class="form-control">
			</div>
		</div>

		<div class="form-group">
			<label for="url" class="col-sm-2 control-label">URL</label>
			<div class="col-sm-5">
				<div class="input-group">
					<span class="input-group-addon">http://</span><input type="text" size="16" name="url" id="url" value="<?php echo set_value('url'); ?>" class="form-control"><span class="input-group-addon">.<?php echo $this->config->item('domain'); ?></span>
				</div>
			</div>
		</div>
		
		<div class="form-group">
			<label for="username" class="col-sm-2 control-label">Gebruikersnaam</label>
			<div class="col-sm-3">
				<input type="text" name="username" id="username" value="admin" class="form-control">
			</div>
		</div>

		<div class="form-group">
			<label for="password" class="col-sm-2 control-label">Wachtwoord</label>
			<div class="col-sm-3">
				<input type="password" name="password" id="password" value="" class="form-control" autocomplete="off">
				<span class="help-text">Leeg laten = automatisch gegenereerd wachtwoord</span>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-5">
				<button class="btn btn-primary" type="submit">Toevoegen</button>
			</div>
		</div>
	</fieldset>
</form>