<div>
	<!--<p><?php echo lang('upload.keywords_text'); ?></p>-->
	
	<div id="keywords-container" style="margin-bottom: 15px; display: none;" >	
		<input type="text" value="" name="keywords" id="keywords" placeholder="+ Trefwoord" />		
	</div>
	
	<p>
		<strong>Toegestaande extensies:</strong>
		<?php foreach($extensions as $extension): ?>
			<span class="label label-info"><?php echo $extension; ?></span>
		<?php endforeach; ?>
	</p>
				
	<div id="file-uploader"></div>
	
	<script>var button_text = '<?php echo lang('upload.button'); ?>';</script>
	<link href="<?php echo base_url(); ?>css/fileuploader.css" rel="stylesheet" type="text/css">	
	<script src="<?php echo base_url(); ?>js/fileuploader.js" type="text/javascript"></script>
	<script>								
		$(function(){
			var keywords = '';
			var currentTime = <?php echo time(); ?>;

			var uploader = new qq.FileUploader({
				element: document.getElementById('file-uploader'),
				params: {
					currentTime: currentTime
				},
				maxConnections: 1,
				action: '/upload/handle_upload',
				allowedExtensions: <?php echo json_encode($extensions); ?>,
				debug: false,
				onSubmit: function(id, fileName){
					//if($.trim(keywords) == '') {
						//setTimeout(function(){ alert('Er moet minimaal 1 trefwoord toegevoegd worden om een bestand te kunnen uploaden.'); }, 1);
						//return false;
					//} else {						
						$("#keywords").remove();
						
						var html = '';
						var keywords_array = keywords.split(",");
						if(keywords != '' && keywords_array.length > 0) {
							for(var i = 0; i < keywords_array.length; i+=1) {
								html += '<a href="#" class="btn btn-info btn-xs btn-keyword" style="margin-bottom: 3px;">'+keywords_array[i]+'</a> ';
							}
						}
						
						$("#keywords-container").html(html);
						$(".hide-on-upload").hide();
					//}
				},
				onComplete: function(id, fileName, responseJSON){				
					if($(".qq-upload-list").find('li').length == $(".qq-upload-list").find('li.qq-upload-success').length){
						window.location.href = '/upload?success=1&time=' + currentTime;
					}
				}
			});
			
			addTagsInput($("#keywords"), function(){
				keywords = $(this).val();
				uploader.setParams({
				   keywords: $(this).val(),
				   currentTime: currentTime
				});
				if($.trim(keywords) == '') {
					$(".qq-upload-button").css('opacity', .6);
				} else {
					$(".qq-upload-button").css('opacity', 1);
				}
			});
		});
	</script>
</div>

<?php if(!empty($images_group)): ?>
	<div class="hide-on-upload">
		<hr />
		
		<div class="clearfix">
			<a href="" class="btn btn-danger js-delete-selected pull-right hide" style="margin-top: 17px;"><span class="glyphicon glyphicon-trash"></span> Geselecteerde bestanden verwijderen</a>
			<h2 class="pull-left"><?php echo lang('upload.uploaded_title'); ?></h2>
		</div>

		<form action="/upload/save" method="post" class="form-horizontal">
			<fieldset>
				<div class="panel-group" id="accordion">
					<?php $i = 0; ?>
					<?php foreach($images_group as $timestamp => $images): ?>
					<div class="panel panel-default" style="overflow: visible;">
						<div class="panel-heading">
							<h4 class="panel-title">
								<a data-toggle="collapse" data-parent="#accordion" href="#collapse-<?php echo $timestamp; ?>">
									<strong><?php echo strftime("%#d %B", $timestamp); ?>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo date("H:i", $timestamp) ?></strong>
								</a>
								<a class="btn btn-xs btn-default pull-right select-all" href="#">Selecteer alles</a>
							</h4>
							
						</div>
						<div id="collapse-<?php echo $timestamp; ?>" class="panel-collapse collapse <?php if(TRUE || $time == $timestamp): ?>in<?php endif; ?>">
							<div class="panel-body">
								<!--<a href="" class="btn btn-default js-main-keywords"><span class="glyphicon glyphicon-plus"></span> Algemene trefwoorden toevoegen</a>-->
								
								<!--<div class="main-keywords well" style="display: none; margin-top: 5px;">-->
									<h4>Algemene trefwoorden</h4>
									<p>Voeg hieronder algemene trefwoorden (komma gescheiden) toe die van toepassing zijn op alle onderstaande bestanden in dit blok.</p>
									<input type="text" value="" name="main_keywords[<?php echo $timestamp; ?>]" class="main-keywords-input" placeholder="+ Trefwoord" />
									<input type="submit" name="submit" class="submit btn btn-default" value="Voeg toe" style="margin-top: 3px;" />
								<!--</div>-->
								
								<div class="row">
									<?php foreach($images as $image): ?>
									<div class="col-md-6">
										<div class="row" style="margin-top: 20px;">
											<div class="col-md-5"><img src="<?php echo resize($image['client_id'], $image['file'], 80 * 2.5, 60 * 2.5); ?>" alt="" class="img-responsive thumbnail" data-image_id="<?php echo $image['image_id']; ?>" data-placement="right" /></div>
											<div class="col-md-7">
												<input type="text" value="<?php echo $image['name']; ?>" name="names[<?php echo $image['image_id']; ?>]" placeholder="<?php echo lang('upload.row.filename'); ?>" class="form-control" style="margin-bottom: 5px;" />
												<input name="keywords[<?php echo $image['image_id']; ?>]" class="keywords-image" value="<?php echo $image['keywords_string']; ?>" style="width: 300px;" />
											
												<div class="pull-right" style="margin-top: 5px;">
													<a href="/images/info/<?php echo $image['image_id']; ?>" class="btn btn-default btn-xs open"><span class="glyphicon glyphicon-eye-open"></span> <?php echo lang('upload.row.view'); ?></a>
													<a href="/upload/delete/<?php echo $image['image_id']; ?>" class="btn btn-danger btn-xs delete-warning"><span class="glyphicon glyphicon-trash"></span> <?php echo lang('upload.row.delete'); ?></a>
													<input type="checkbox" name="select[]" class="file-select" value="<?php echo $image['image_id']; ?>" />
												</div>
											</div>
										</div>
									</div>
									<?php endforeach; ?>
								</div>
							</div>
						</div>
					</div>
					<?php endforeach; ?>
				</div>
				<div class="floating-button"<?php if(empty($images_group)): ?> style="display: none;"<?php endif; ?>><button class="btn btn-primary btn-lg pull-right" type="submit"><?php echo lang('save'); ?></button></div>
			</fieldset>
		</form>
	</div>
	
	<script type="text/javascript">
	$(function(){
		$(".js-main-keywords").on('click', function(){
			$(this).parents('.panel').find('.main-keywords').slideToggle(200);
			return false;
		});
		
		$(".main-keywords-input").each(function(){ 
			var $t = $(this);
			$t.parent().find('.submit').on('click', function(){
				var $k = $(this).parents('.panel').find('.keywords-image');
				$k.each(function(){
					
					$(this).importTags($t.val());
					//$k.importTags();
				});
				
				$(this).parents('.panel').find('.main-keywords').slideToggle(200);
				
				return false;
			});
			addTagsInput($t, function(){
			});
		});	
		
		$(".keywords-image").each(function(){
			addTagsInput($(this), function(){
			});
		});
		
		$(".panel-title a").on('click', function(){
			$(".floating-button").show();
		});
		
		var delete_ids;
		$(".file-select").on('change', function(){
			delete_ids = $('.file-select:checked').map(function() {return this.value;}).get().join(',');
			$(".js-delete-selected").removeClass('hide');
			if(delete_ids == '') $(".js-delete-selected").addClass('hide');
		});
		
		$('.select-all').on('click',function(){					
			setProperty = true;
			if($(".file-select:checked", $(this).parents('.panel')).length > 0)
				setProperty = false;
							
			$(".file-select", $(this).parents('.panel')).each(function(){				
				$(this).prop('checked', setProperty);
			});

			$('.file-select').trigger('change');
			return false;
		});
		
		
		$(".js-delete-selected").on('click', function(){
			if(!confirm('Weet u zeker dat u al deze bestanden wilt verwijderen?'))
				return false;
		
			window.location.href = '/upload/delete/' + delete_ids;
			
			return false;
		});
	});
	</script>
	
<?php endif; ?>

<div class="hide-on-upload">
	<a href="/upload/log" class="btn btn-default">Bekijk upload log</a>
</div>