<div class="btn-bar">
	<a href="/#!<?php echo $image_id; ?>" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i> Terug</a>
</div>

<form action="/images/edit/<?php echo $image_id; ?>" method="post" class="form-horizontal">
	<fieldset>
		<div class="form-group">
			<label for="name" class="col-sm-2 control-label">Naam</label>
			<div class="col-sm-3">
				<input type="text" name="name" id="name" value="<?php echo $image['name']; ?>" class="form-control">
			</div>
		</div>
		
		<div class="form-group">
			<label for="notes" class="col-sm-2 control-label">Trefwoorden</label>
			<div class="col-sm-3">
				<input name="keywords" id="keywords" value="<?php echo implode(",", $keywords); ?>" class="keywords form-control" />
			</div>
		</div>
		
		<div class="form-group">
			<label for="notes" class="col-sm-2 control-label">Notities</label>
			<div class="col-sm-3">
				<textarea rows="3" id="notes" name="notes" class="form-control"><?php echo $image['notes']; ?></textarea>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-5">
				<button class="btn btn-primary" type="submit">Wijzigen</button>
			</div>
		</div>
	</fieldset>
</form>
