<div class="btn-bar">
	<a href="/<?php if(count($image_ids) == 1): ?>images/info/<?php echo reset($image_ids); ?><?php endif; ?>" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i> Terug</a>
</div>

<form action="" method="post" class="form-horizontal">
	<fieldset>	
		<div class="form-group">
			<label for="to" class="col-sm-2 control-label">Bestand(en)</label>
			<div class="col-sm-7">
				<p class="form-control-static">
					<?php foreach($images as $image): ?>
						- <a href="/images/info/<?php echo $image['image_id']; ?>"><?php echo $image['name']; ?></a><br />
					<?php endforeach; ?>
				</p>
			</div>
		</div>
		
		<div class="form-group">
			<label for="from" class="col-sm-2 control-label">E-mail afzender</label>
			<div class="col-sm-3">
				<input type="email" name="from" id="from" value="" class="form-control">
			</div>
		</div>
		
		<div class="form-group">
			<label for="to" class="col-sm-2 control-label">Ontvanger e-mail</label>
			<div class="col-sm-3">
				<input type="text" name="to" id="to" value="" class="form-control">
			</div>
		</div>
		
		<div class="form-group">
			<label for="message" class="col-sm-2 control-label">Bericht</label>
			<div class="col-sm-3">
				<textarea rows="3" id="message" name="message" class="form-control"></textarea>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-5">
				<button class="btn btn-primary" type="submit">Versturen</button>
			</div>
		</div>
	</fieldset>
</form>
