<div class="btn-bar">
	<a href="/users" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i> Terug</a>
</div>

<form action="<?php echo base_url(); ?>users/edit/<?php echo $user_id; ?>" method="post" class="form-horizontal">
	<fieldset>
		<div class="form-group">
			<label for="username" class="col-sm-2 control-label">Gebruikersnaam</label>
			<div class="col-sm-3">
				<p class="form-control-static"><?php echo $user['username']; ?></p>
			</div>
		</div>
		<?php /*<script type="text/javascript">
			// Dit stukje code is nodig voor een bugfix op safari (mac) (autocomplete username / password) 
			$(document).ready(function(){		
				var ua = navigator.userAgent.toLowerCase();
				can_remove = 0;
				if(ua.indexOf('safari') > -1){	
					$('div.form-group').first().prepend('<span id="safari-bug-fix" style="position:absolute;top:-100px;"></span>');
					$('#safari-bug-fix').html('<input type="text" name="fake_data[name]" style="position:absolute;top:-100px;" /><input type="password" name="fake_data[password]" style="position:absolute;top:-100px;"  />');									
					var can_remove = 1;
				}
				if(can_remove==1){
					setInterval(function(){
						$('#safari-bug-fix').remove();
					},1000);
				}
			});		
		</script>*/ ?>
		
		
		<input style="display:none" type="text" name="fakeusernameremembered"/>
		<input style="display:none" type="password" name="fakepasswordremembered"/>
		
		<div class="form-group">
			<label for="company_name" class="col-sm-2 control-label">Bedrijfsnaam</label>
			<div class="col-sm-3">
				<input type="text" name="company_name" id="company_name" value="<?php echo $user['company_name']; ?>" class="form-control">
			</div>
		</div>
		
		<div class="form-group">
			<label for="first_name" class="col-sm-2 control-label">Naam</label>
			<div class="col-sm-5">
				<div class="row">
					<div class="col-xs-4">
						<input type="text" name="first_name" id="first_name" value="<?php echo $user['first_name']; ?>" class="form-control" placeholder="Voornaam">
					</div>
					<div class="col-xs-4">
						<input type="text" name="middle_name" id="middle_name" value="<?php echo $user['middle_name']; ?>" class="form-control" placeholder="Tussenv.">
					</div>
					<div class="col-xs-4">
						<input type="text" name="last_name" id="last_name" value="<?php echo $user['last_name']; ?>" class="form-control" placeholder="Achternaam">
					</div>
				</div>
			</div>
		</div>
		
		<div class="form-group">
			<label for="email" class="col-sm-2 control-label">E-mail</label>
			<div class="col-sm-3">			
				<input type="email" name="email" id="email" value="<?php echo $user['email']; ?>" class="form-control">
			</div>
		</div>
		
		<div class="form-group">
			<label for="address" class="col-sm-2 control-label">Adres</label>
			<div class="col-sm-3">
				<input type="text" name="address" id="address" value="<?php echo $user['address']; ?>" class="form-control">
			</div>
		</div>
		
		<div class="form-group">
			<label for="postal_code" class="col-sm-2 control-label">Postcode</label>
			<div class="col-sm-3">
				<input type="text" name="postal_code" id="postal_code" value="<?php echo $user['postal_code']; ?>" class="form-control">
			</div>
		</div>
		
		<div class="form-group">
			<label for="postal_code" class="col-sm-2 control-label">Plaats</label>
			<div class="col-sm-3">
				<input type="text" name="place" id="place" value="<?php echo $user['place']; ?>" class="form-control">
			</div>
		</div>
		
		<div class="form-group">
			<label for="postal_code" class="col-sm-2 control-label">Telefoonnummer</label>
			<div class="col-sm-3">
				<input type="text" name="phone_number" id="phone_number" value="<?php echo $user['phone_number']; ?>" class="form-control">
			</div>
		</div>
		
		<?php if($user['user_id'] != user_id()): ?>
		<div class="form-group">
			<label for="admin" class="col-sm-2 control-label">Type</label>
			<div class="col-sm-6">
				<div class="radio"><label><input type="radio" value="admin" name="type" <?php echo set_radio('type', 'admin', ($user['type'] == 'admin')); ?> /> Administrator</label></div>
				<p class="help-block">Kan gebruikers aanmaken, wijzigen en verwijderen, instellingen wijzigen, categorieën beheren en bestanden up- en downloaden, wijzigen en verwijderen.</p>
				
				<div class="radio"><label><input type="radio" value="downloader" name="type" <?php echo set_radio('type', 'downloader', ($user['type'] == 'downloader')); ?> /> Downloader</label></div>
				<p class="help-block">Kan alleen bestanden downloaden uit ImageShare.</p>
				
				<div class="radio"><label><input type="radio" value="uploader" name="type" <?php echo set_radio('type', 'uploader', ($user['type'] == 'uploader')); ?> /> Up- & downloader</label></div>
				<p class="help-block">Kan bestanden up- en downloaden en zijn eigen toegevoegde bestanden wijzigen.</p>
				
				<div class="radio"><label><input type="radio" value="readonly" name="type" <?php echo set_radio('type', 'readonly', ($user['type'] == 'readonly')); ?> /> Readonly</label></div>
				<p class="help-block">Kan bestanden alleen bekijken.</p>
			</div>
		</div>
		<?php endif; ?>
		
		<div class="form-group">
			<label for="admin" class="col-sm-2 control-label">Status</label>
			<div class="col-sm-3">
				<div class="radio"><label><input type="radio" value="1" name="active" <?php if($user['active']): ?>checked<?php endif; ?> /> Actief</label></div>
				<div class="radio"><label><input type="radio" value="0" name="active" <?php if(!$user['active']): ?>checked<?php endif; ?> /> Inactief</label></div>
			</div>
		</div>
		
		<div class="form-group<?php if($user['active'] == '0'): ?> hide<?php endif; ?>" id="expire_date">
			<label for="expire_date" class="col-sm-2 control-label">Verloopdatum</label>
			<div class="col-sm-3">				
				<input type="text" id="expire_date" name="expire_date" class="form-control datepicker" value="<?php echo (empty($user['expire_date']) ? '' : date("d-m-Y", $user['expire_date'])); ?>" autocomplete="off" />
			</div>
		</div>
		
		<div class="form-group">
			<label for="new_password" class="col-sm-2 control-label">Nieuw wachtwoord</label>
			<div class="col-sm-3">
				<input type="password" name="new_password" id="new_password" value="" class="form-control" autocomplete="off">
				<span class="help-block">Laat leeg om het wachtwoord niet aan te passen.</span>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-5">
				<button class="btn btn-primary" type="submit">Wijzigen</button>
			</div>
		</div>
	</fieldset>
	
	
	
</form>